server:
  port: 8084
  servlet:
    context-path: /api/v1/analytics

spring:
  application:
    name: analytics-service
  datasource:
    url: jdbc:postgresql://localhost:5432/worksphere_analytics
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
