import { useLocation, Link } from 'react-router-dom'

const breadcrumbMap = {
  dashboard: { label: 'Dashboard' },
  employees: { label: 'Employees' },
  attendance: { label: 'Attendance' },
  payroll: { label: 'Payroll' },
  recruitment: { label: 'Recruitment' },
  projects: { label: 'Projects' },
  assets: { label: 'Assets' },
  compliance: { label: 'Compliance' },
  performance: { label: 'Performance' },
  administration: { label: 'Administration' },
  settings: { label: 'Settings' },
  leave: { label: 'Leave' },
  finance: { label: 'Finance' },
  budget: { label: 'Budget' },
  expenses: { label: 'Expenses' },
  tax: { label: 'Tax' },
  campaigns: { label: 'Campaigns' },
  content: { label: 'Content' },
  pipeline: { label: 'Pipeline' },
  clients: { label: 'Clients' },
  revenue: { label: 'Revenue' },
  engineering: { label: 'Engineering' },
  devops: { label: 'DevOps' },
  'code-reviews': { label: 'Code Reviews' },
  'pull-requests': { label: 'Pull Requests' },
  'ci/cd': { label: 'CI/CD' },
  infrastructure: { label: 'Infrastructure' },
  monitoring: { label: 'Monitoring' },
  'test-plans': { label: 'Test Plans' },
  'test-runs': { label: 'Test Runs' },
  bugs: { label: 'Bugs' },
  automation: { label: 'Automation' },
  tasks: { label: 'Tasks' },
  sprints: { label: 'Sprints' },
  threats: { label: 'Threats' },
  'audit-logs': { label: 'Audit Logs' },
  vulnerabilities: { label: 'Vulnerabilities' },
  tickets: { label: 'Tickets' },
  'knowledge-base': { label: 'Knowledge Base' },
  sla: { label: 'SLA' },
  learning: { label: 'Learning' },
  timeline: { label: 'Timeline' },
  team: { label: 'Team' },
  analytics: { label: 'Analytics' },
  security: { label: 'Security' },
  allocations: { label: 'Allocations' },
  'org-chart': { label: 'Organization Chart' },
  // cto routes
  cto: { label: 'CTO Dashboard' },
  'executive-overview': { label: 'Executive Overview' },
  'team-performance': { label: 'Team Performance' },
  'engineering-analytics': { label: 'Engineering Analytics' },
  'sprint-dashboard': { label: 'Sprint Dashboard' },
  'code-quality': { label: 'Code Quality' },
  'code-coverage': { label: 'Code Coverage' },
  'technical-debt': { label: 'Technical Debt' },
  releases: { label: 'Releases' },
  'cicd-pipelines': { label: 'CI/CD Pipelines' },
  deployments: { label: 'Deployments' },
  'build-status': { label: 'Build Status' },
  rollbacks: { label: 'Rollbacks' },
  'release-calendar': { label: 'Release Calendar' },
  'active-projects': { label: 'Active Projects' },
  'project-portfolio': { label: 'Project Portfolio' },
  'sprint-board': { label: 'Sprint Board' },
  roadmap: { label: 'Roadmap' },
  milestones: { label: 'Milestones' },
  'resource-allocation': { label: 'Resource Allocation' },
  'system-architecture': { label: 'System Architecture' },
  microservices: { label: 'Microservices' },
  'api-gateway': { label: 'API Gateway' },
  'service-dependencies': { label: 'Service Dependencies' },
  'database-architecture': { label: 'Database Architecture' },
  servers: { label: 'Servers' },
  kubernetes: { label: 'Kubernetes' },
  docker: { label: 'Docker' },
  'virtual-machines': { label: 'Virtual Machines' },
  storage: { label: 'Storage' },
  network: { label: 'Network' },
  cloud: { label: 'Cloud Operations' },
  aws: { label: 'AWS' },
  azure: { label: 'Azure' },
  gcp: { label: 'Google Cloud' },
  'cloud-cost': { label: 'Cloud Cost' },
  'auto-scaling': { label: 'Auto Scaling' },
  'backup-recovery': { label: 'Backup & Recovery' },
  'system-health': { label: 'System Health' },
  'application-health': { label: 'Application Health' },
  uptime: { label: 'Uptime' },
  'error-logs': { label: 'Error Logs' },
  'alert-center': { label: 'Alert Center' },
  'security-dashboard': { label: 'Security Dashboard' },
  'threat-intelligence': { label: 'Threat Intelligence' },
  siem: { label: 'SIEM' },
  'zero-trust': { label: 'Zero Trust' },
  'infrastructure-as-code': { label: 'Infrastructure as Code' },
  containers: { label: 'Containers' },
  'secrets-management': { label: 'Secrets Management' },
  'ai-models': { label: 'AI Models' },
  'llm-configuration': { label: 'LLM Configuration' },
  'ai-analytics': { label: 'AI Analytics' },
  'prompt-management': { label: 'Prompt Management' },
  'gpu-usage': { label: 'GPU Usage' },
  'ai-cost': { label: 'AI Cost' },
  databases: { label: 'Databases' },
  'data-warehouse': { label: 'Data Warehouse' },
  'etl-jobs': { label: 'ETL Jobs' },
  'backup-status': { label: 'Backup Status' },
  'data-quality': { label: 'Data Quality' },
  'cloud-billing': { label: 'Cloud Billing' },
  'software-licenses': { label: 'Software Licenses' },
  'infrastructure-cost': { label: 'Infrastructure Cost' },
  'vendor-contracts': { label: 'Vendor Contracts' },
  rd: { label: 'R&D' },
  'proof-of-concepts': { label: 'Proof of Concepts' },
  'technology-roadmap': { label: 'Technology Roadmap' },
  'emerging-technologies': { label: 'Emerging Technologies' },
  vendors: { label: 'Vendors' },
  contracts: { label: 'Contracts' },
  renewals: { label: 'Renewals' },
  'executive-reports': { label: 'Executive Reports' },
  'engineering-reports': { label: 'Engineering Reports' },
  'infrastructure-reports': { label: 'Infrastructure Reports' },
  'cost-reports': { label: 'Cost Reports' },
  'security-reports': { label: 'Security Reports' },
  'infrastructure-requests': { label: 'Infrastructure Requests' },
  'production-deployments': { label: 'Production Deployments' },
  'software-purchases': { label: 'Software Purchases' },
  'cloud-budget-requests': { label: 'Cloud Budget Requests' },
  'engineering-meetings': { label: 'Engineering Meetings' },
  'architecture-reviews': { label: 'Architecture Reviews' },
  'sprint-planning': { label: 'Sprint Planning' },
  'executive-meetings': { label: 'Executive Meetings' },
  notifications: { label: 'Notifications' },
  // intern routes
  intern: { label: 'Intern Dashboard' },
  'clock-in': { label: 'Clock In' },
  'clock-out': { label: 'Clock Out' },
  'work-hours': { label: 'Work Hours' },
  apply: { label: 'Apply Leave' },
  balance: { label: 'Leave Balance' },
  holidays: { label: 'Holiday Calendar' },
  paths: { label: 'Learning Paths' },
  assessments: { label: 'Assessments' },
  quizzes: { label: 'Quizzes' },
  progress: { label: 'Progress Tracking' },
  assigned: { label: 'Assigned' },
  my: { label: 'My Tasks' },
  board: { label: 'Task Board' },
  completed: { label: 'Completed' },
  pending: { label: 'Pending' },
  files: { label: 'Files' },
  mentor: { label: 'Mentorship' },
  sessions: { label: '1-on-1 Sessions' },
  knowledge: { label: 'Knowledge Base' },
  docs: { label: 'Documentation' },
  standards: { label: 'Coding Standards' },
  sops: { label: 'SOPs' },
  documents: { label: 'Documents' },
  'offer-letter': { label: 'Offer Letter' },
  'internship-letter': { label: 'Internship Letter' },
  completion: { label: 'Completion Certificate' },
  hr: { label: 'HR Documents' },
  weekly: { label: 'Weekly Reviews' },
  monthly: { label: 'Monthly Reviews' },
  final: { label: 'Final Evaluation' },
  members: { label: 'Members' },
  directory: { label: 'Directory' },
  chat: { label: 'Communication' },
  direct: { label: 'Direct Messages' },
  announcements: { label: 'Announcements' },
  webmail: { label: 'Webmail' },
  schedule: { label: 'Schedule' },
  notes: { label: 'Meeting Notes' },
  helpdesk: { label: 'Help Desk' },
  it: { label: 'IT Support' },
  ticket: { label: 'Raise Ticket' },
  // employee sub-routes
  profile: { label: 'Employee Profile' },
  users: { label: 'User Management' },
  rbac: { label: 'RBAC Matrix' },
  'ai-config': { label: 'AI & System Config' },
  audit: { label: 'Global Audit Logs' },
  tracking: { label: 'Global Tracking' },
  reports: { label: 'Activity Reports' },
}

export default function Breadcrumbs() {
  const location = useLocation()
  const segments = location.pathname.split('/').filter(Boolean)

  if (segments.length === 0) return null

  const crumbs = segments.map((seg, i) => {
    const entry = breadcrumbMap[seg]
    return {
      label: entry?.label || seg.charAt(0).toUpperCase() + seg.slice(1).replace(/-/g, ' '),
      path: '/' + segments.slice(0, i + 1).join('/'),
      isLast: i === segments.length - 1,
    }
  })

  return (
    <nav className="flex items-center gap-1.5 text-xs text-tertiary mb-3" aria-label="Breadcrumb">
      <Link to="/dashboard" className="hover:text-link transition-colors duration-150">
        <svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
          <path strokeLinecap="round" strokeLinejoin="round" d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6" />
        </svg>
      </Link>
      {crumbs.map((crumb, i) => (
        <span key={crumb.path} className="flex items-center gap-1.5">
          <svg className="w-3 h-3 text-tertiary" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
            <path strokeLinecap="round" strokeLinejoin="round" d="M9 5l7 7-7 7" />
          </svg>
          {crumb.isLast ? (
            <span className="text-primary font-medium">{crumb.label}</span>
          ) : (
            <Link to={crumb.path} className="hover:text-link transition-colors duration-150">{crumb.label}</Link>
          )}
        </span>
      ))}
    </nav>
  )
}
