pipeline {
    agent any
    environment {
        DOCKER_REGISTRY = '123456789012.dkr.ecr.us-east-1.amazonaws.com'
        EKS_CLUSTER     = 'worksphere-eks-cluster'
    }
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/GaganCB2002/WorkSphere-Enterprise-Grade-Activity-Intelligence.git'
            }
        }
        stage('Maven Build & SonarQube') {
            steps {
                dir('apps/enterprise-monitoring-system/backend') {
                    sh './mvnw clean verify sonar:sonar -Dsonar.projectKey=worksphere-backend'
                }
            }
        }
        stage('Docker Build & ECR Push') {
            steps {
                sh '$(aws ecr get-login --no-include-email --region us-east-1)'
                sh 'docker build -t ${DOCKER_REGISTRY}/worksphere-gateway:latest apps/enterprise-monitoring-system/microservices/gateway-service'
                sh 'docker push ${DOCKER_REGISTRY}/worksphere-gateway:latest'
            }
        }
        stage('Kubernetes Deploy') {
            steps {
                sh 'aws eks update-kubeconfig --name ${EKS_CLUSTER} --region us-east-1'
                sh 'kubectl apply -f apps/enterprise-monitoring-system/deployment/kubernetes/'
            }
        }
    }
}
