/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx,jsx}'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        display: ['Outfit', 'sans-serif'],
        headline: ['EB Garamond', 'serif'],
        body: ['Manrope', 'sans-serif'],
        label: ['Manrope', 'sans-serif'],
      },
      colors: {
        pastry: {
          primary: '#4B49AC',
          'primary-light': '#98BDFF',
          'blue-light': '#7DA0FA',
          'purple-light': '#7978E9',
          coral: '#F3797E',
        },
        brand: '#4B49AC',
        "on-primary-fixed-variant": "#8a4518",
        "primary-fixed": "#fbe8d8",
        "tertiary-fixed-dim": "#e8a0a0",
        "tertiary-fixed": "#fce0e0",
        "secondary-fixed-dim": "#cec6be",
        "on-secondary": "#ffffff",
        "primary-container": "#e08850",
        "on-secondary-fixed": "#2a2420",
        "surface-container-high": "#ece6dc",
        "on-surface-variant": "#605850",
        "background": "#FAF6F0",
        "surface-container-highest": "#e6e0d6",
        "on-secondary-fixed-variant": "#504840",
        "error-container": "#fce4e0",
        "outline-variant": "#EFE6DD",
        "inverse-primary": "#f0a878",
        "on-error-container": "#7a1a10",
        "surface-tint": "#C2652A",
        "on-error": "#ffffff",
        "secondary": "#78706a",
        "on-primary": "#ffffff",
        "surface-container-low": "#FFFFFF",
        "secondary-fixed": "#eae2da",
        "surface-dim": "#dcd6cc",
        "surface-container": "#F5EFEB",
        "on-tertiary-container": "#3a2020",
        "on-primary-container": "#fbe8d8",
        "inverse-surface": "#2B221E",
        "tertiary": "#8c3c3c",
        "surface-bright": "#FAF6F0",
        "tertiary-container": "#d47070",
        "on-secondary-container": "#605850",
        "surface": "#FAF6F0",
        "on-tertiary-fixed": "#2e1515",
        "secondary-container": "#eae2da",
        "primary": "#C2652A",
        "outline": "#9a9088",
        "on-tertiary-fixed-variant": "#6e3030",
        "on-primary-fixed": "#401a08",
        "surface-container-lowest": "#ffffff",
        "surface-variant": "#ece6dc",
        "on-tertiary": "#ffffff",
        "on-surface": "#3a302a",
        "error": "#c0392b",
        "on-background": "#3a302a",
        "primary-fixed-dim": "#f0a878",
        "inverse-on-surface": "#faf5ee"
      },
      boxShadow: {
        premium: '0 30px 100px rgba(0, 0, 0, 0.5)',
        pastry: '0 8px 32px rgba(75, 73, 172, 0.15)',
        soft: '0 2px 16px rgba(58, 48, 42, 0.04)',
        warm: '0 4px 20px rgba(194, 101, 42, 0.12)',
      },
      backgroundImage: {
        'pastry-gradient': 'linear-gradient(135deg, #4B49AC 0%, #98BDFF 50%, #7DA0FA 100%)',
        'pastry-soft': 'linear-gradient(180deg, #f8f6ff 0%, #eef3ff 100%)',
      },
    },
  },
  plugins: [],
}
